version: '1.0'

services:
  server:
    build: ./server
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=jkljkl
      - POSTGRES_DB=db_dev
  
  client:
    build: ./client/front-end
    volumes:
      - ./client/front-end:/app
      - /app/node_modules
    ports:
      - 5173:5173
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev


volumes:
  postgres_data: